version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"  # Expose port 27017 to access MongoDB locally

  flask-api:
    build: .
    container_name: treasurebook-api
    environment:
      - MONGO_HOST=mongodb  # MongoDB hostname (service name)
    ports:
      - "5000:5000"
    depends_on:
      - mongodb  # Ensure MongoDB starts before Flask API
    restart: always

volumes:
  mongo-data:
